export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const SET_MY_PROFILE = 'SET_MY_PROFILE';

export const GET_MY_MEETUP_CREATED = 'GET_MY_MEETUP_CREATED';
export const SET_MY_MEETUP_CREATED = 'SET_MY_MEETUP_CREATED';

export const GET_MY_MEETUP_ATTENDED = 'GET_MY_MEETUP_ATTENDED';
export const SET_MY_MEETUP_ATTENDED = 'SET_MY_MEETUP_ATTENDED';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const DELETE_MEETUP = 'DELETE_MEETUP';

export const RESET_MY_PROFILE = 'RESET_MY_PROFILE';