export const GET_DETAIL_MEETUP = 'GET_DETAIL_MEETUP';
export const SET_DETAIL_MEETUP = 'SET_DETAIL_MEETUP';

export const GET_MEMBER_MEETUP = 'GET_MEMBER_MEETUP';
export const SET_MEMBER_MEETUP = 'SET_MEMBER_MEETUP';

export const ADD_ATTEND_MEETUP = 'ADD_ATTEND_MEETUP';
export const DELETE_ATTEND_MEETUP = 'DELETE_ATTEND_MEETUP';

export const GET_COMMENT_MEETUP = 'GET_COMMENT_MEETUP';
export const LOAD_MORE_COMMENT_MEETUP = 'LOAD_MORE_COMMENT_MEETUP';
export const SET_COMMENT_MEETUP = 'SET_COMMENT_MEETUP';
export const ADD_COMMENT_MEETUP = 'ADD_COMMENT_MEETUP';
export const RESET_COMMENT_MEETUP = 'RESET_COMMENT_MEETUP';